### PR TITLE
more detail on how to initiate voting

### PR DESCRIPTION
**Pull request by oetiker**

### CODE REVIEW

**Comment by derrell** [comment]
Fine with me, except that I'd never remember that string. I see that you can do colon followed by something to see available icons. I'd just need to remember that it's for a ballot. @oetiker, you'll normally be calling for votes, I suspect, so as long as you can remember this...

**Comment by cajus** [comment]
That's what the wiki is for ;-) I like the way, because the vote entry gains some more visibility this way.

**Comment by derrell** [comment]
I agree. It's much more visible with the ballot mark, and makes sense to do it.

**Comment by oetiker** [comment]
so you could merge and then publish the wiki :)

**Pull request merged**
